import { supabase } from '../../config/db.js';

/**
 * GrowthRecommendationRepository
 * Data Access Layer for Growth Recommendations generated by the Rule Engine.
 */
class GrowthRecommendationRepository {
    
    async getRecommendations(userId, { page = 1, limit = 20, status = 'PENDING' } = {}) {
        const offset = (page - 1) * limit;
        
        const { data, count, error } = await supabase
            .from('growth_recommendations')
            .select(`
                *,
                opportunity:opportunity_id (*)
            `, { count: 'exact' })
            .eq('user_id', userId)
            .eq('status', status)
            .order('priority', { ascending: false }) // Highest priority first
            .order('created_at', { ascending: false })
            .range(offset, offset + limit - 1);

        if (error) throw error;
        return { data, total: count, page, limit };
    }

    async upsertRecommendation(userId, recData) {
        // We use upsert based on title/category to prevent duplicate identical recommendations,
        // though Supabase needs a unique constraint for simple upsert. For now, doing a basic insert or update.
        // A robust system would check if a pending recommendation of this type already exists.
        
        // Simple duplicate check:
        const { data: existing } = await supabase
            .from('growth_recommendations')
            .select('id')
            .eq('user_id', userId)
            .eq('title', recData.title)
            .eq('status', 'PENDING')
            .single();

        if (existing) {
            // Update priority or AI enhancement if it exists
            const { data, error } = await supabase
                .from('growth_recommendations')
                .update({ ...recData, updated_at: new Date().toISOString() })
                .eq('id', existing.id)
                .select()
                .single();
            if (error) throw error;
            return data;
        } else {
            const { data, error } = await supabase
                .from('growth_recommendations')
                .insert({
                    user_id: userId,
                    ...recData
                })
                .select()
                .single();
            if (error) throw error;
            return data;
        }
    }

    async updateStatus(id, status) {
        const { data, error } = await supabase
            .from('growth_recommendations')
            .update({ status, updated_at: new Date().toISOString() })
            .eq('id', id)
            .select()
            .single();

        if (error) throw error;
        return data;
    }
}

export default new GrowthRecommendationRepository();
