-- Migration 50: Growth Domain
-- Run in Supabase Dashboard SQL Editor

-- Reference table for Government Schemes & Funding
CREATE TABLE IF NOT EXISTS public.growth_opportunities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    type TEXT NOT NULL CHECK (type IN ('GOVERNMENT_SCHEME', 'FUNDING_PROGRAM', 'PARTNERSHIP')),
    name TEXT NOT NULL,
    description TEXT,
    eligibility_criteria JSONB DEFAULT '{}'::jsonb,
    benefit_details JSONB DEFAULT '{}'::jsonb,
    status TEXT DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Store individual user recommendations generated by the rule engine
CREATE TABLE IF NOT EXISTS public.growth_recommendations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    category TEXT NOT NULL CHECK (category IN ('FUNDING', 'COMPLIANCE', 'SALES', 'INVENTORY', 'MARKETING', 'TAX', 'PROCUREMENT', 'PARTNERSHIPS', 'EXPANSION', 'TRAINING')),
    priority INTEGER DEFAULT 0, -- Higher is more important
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    action_url TEXT,
    opportunity_id UUID REFERENCES public.growth_opportunities(id) ON DELETE SET NULL, -- Null if not linked to a specific scheme
    ai_enhancement JSONB DEFAULT '{}'::jsonb, -- AI generated explanation of why this was recommended
    status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'ACTIONED', 'DISMISSED')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Store business milestones achieved
CREATE TABLE IF NOT EXISTS public.business_milestones (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    milestone_type TEXT NOT NULL,
    achieved_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    context JSONB DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_growth_rec_user ON public.growth_recommendations(user_id, status);
CREATE INDEX IF NOT EXISTS idx_milestones_user ON public.business_milestones(user_id);
