import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { 
    ArrowRight, BarChart2, ShieldCheck, Zap, Layers, Menu, X, CheckSquare, 
    Target, BookOpen, Users, Star, ArrowUpRight, Activity, Cpu, Search, 
    MessageSquare, ChevronDown, ChevronUp, Sparkles, Send, Mic, Play, 
    RefreshCw, Info, Lock, Award, Check 
} from 'lucide-react';
import logo from '../assets/logo.png';

const LandingPage = () => {
    const isLoggedIn = localStorage.getItem('loggedIn');
    const [scrolled, setScrolled] = useState(false);
    const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
    
    // Interactive Dashboard Mockup States
    const [activeTab, setActiveTab] = useState('overview'); // overview, ai, cashflow
    const [chartHovered, setChartHovered] = useState(false);
    const [chartHoverData, setChartHoverData] = useState({ day: 'Fri', sales: '₹48,250', margin: '68.2%' });
    
    // FinVoice Chat States
    const [chatQuery, setChatQuery] = useState('');
    const [isTyping, setIsTyping] = useState(false);
    const [chatMessages, setChatMessages] = useState([
        { 
            sender: 'bot', 
            text: "Hello! I am FinVoice. You can ask me anything about your sales, margins, inventory, or customers in Hindi, English, or Hinglish.",
            timestamp: "10:32 AM" 
        }
    ]);
    
    // Workflow Stepper State
    const [activeStep, setActiveStep] = useState(0);
    
    // FAQ Accordion State
    const [activeFaq, setActiveFaq] = useState(null);

    useEffect(() => {
        const handleScroll = () => {
            setScrolled(window.scrollY > 20);
        };
        window.addEventListener('scroll', handleScroll);
        return () => window.removeEventListener('scroll', handleScroll);
    }, []);

    const navLinks = [
        { name: "Features", href: "#features" },
        { name: "Interactive Demo", href: "#demo" },
        { name: "Subsidy Matcher", href: "#subsidy" },
        { name: "How it Works", href: "#how-it-works" },
        { name: "About Us", href: "#about" },
        { name: "FAQ", href: "#faq" }
    ];

    const scrollToSection = (href) => {
        setMobileMenuOpen(false);
        const element = document.querySelector(href);
        if (element) {
            element.scrollIntoView({ behavior: 'smooth' });
        }
    };

    // FAQ items
    const faqData = [
        {
            q: "How secure is my business financial data on FinSathi?",
            a: "Extremely secure. FinSathi is built with multi-tenant database isolation using PostgreSQL Row-Level Security (RLS) on Supabase. Your ledgers, invoices, and settings are strictly containerized and visible only to your logged-in credentials."
        },
        {
            q: "What is FinVoice AI, and does it support Hinglish queries?",
            a: "FinVoice is our custom NLP assistant. You can speak or type in English, Hindi, or Hinglish (e.g., 'Mera yesterday's profit margin kitna hai?'). It extracts data points securely from your local database and returns natural summaries with beautiful widgets."
        },
        {
            q: "Do I need a paid WhatsApp Business API account for payment reminders?",
            a: "No. FinSathi comes with pre-integrated WhatsApp notification routing. Standard notifications are handled seamlessly. You can also configure your own Meta credentials in the Profile tab to send reminders directly from your personal business handle."
        },
        {
            q: "How does the cash flow crunch prediction work?",
            a: "Our FinPredict engine computes a moving-average run-rate of your daily revenue and supplier outflows over 30 days. It overlay unpaid invoice deadlines to project your cash reserves 14 days forward. If reserves fall below 20%, it flags a 'Cash Crunch Alert'."
        },
        {
            q: "Are the bills generated by the POS terminal GST-compliant?",
            a: "Yes. The FinSathi billing portal automatically computes HSN/SAC parameters, product GST percentages, and splits CGST/SGST/IGST dynamically. It also generates printable PDF bills complete with default Terms of Service and automated payment UPI QR codes."
        }
    ];

    // FinVoice Chat Suggestions
    const chatSuggestions = [
        { label: "Check profit margins", query: "Check today's profit margin" },
        { label: "Low stock items", query: "Show low stock items" },
        { label: "Who owes me money?", query: "Mera customer collections check karo" }
    ];

    const handleSendChat = (queryText) => {
        const text = queryText || chatQuery;
        if (!text.trim()) return;

        // Add user message
        const newMsg = { sender: 'user', text, timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) };
        setChatMessages(prev => [...prev, newMsg]);
        setChatQuery('');
        setIsTyping(true);

        // Simulate AI thinking and replying
        setTimeout(() => {
            let responseText = "";
            let responseComponent = null;

            if (text.toLowerCase().includes('margin') || text.toLowerCase().includes('profit')) {
                responseText = "Today's sales total is ₹48,250 with average gross profit margins of 68.2%. Net margin is ₹32,900. No abnormal discounts detected.";
                responseComponent = (
                    <div className="mt-3 p-3 bg-slate-50 border border-slate-200 rounded-xl space-y-2">
                        <div className="flex justify-between text-[11px] font-bold text-slate-500 uppercase">
                            <span>Metric</span>
                            <span>Value</span>
                        </div>
                        <div className="flex justify-between text-xs text-slate-700">
                            <span>Gross Revenue</span>
                            <span className="font-mono text-emerald-600 font-bold">₹48,250</span>
                        </div>
                        <div className="flex justify-between text-xs text-slate-700">
                            <span>Cost of Goods Sold</span>
                            <span className="font-mono text-slate-500">₹15,350</span>
                        </div>
                        <div className="flex justify-between text-xs font-bold text-slate-800 border-t border-slate-200 pt-1">
                            <span>Net Operating Margin</span>
                            <span className="font-mono text-blue-600 font-bold">₹32,900 (68.2%)</span>
                        </div>
                    </div>
                );
            } else if (text.toLowerCase().includes('stock') || text.toLowerCase().includes('inventory')) {
                responseText = "3 items are running below your safety limit of 10 units. Recommend creating a restock batch for supplier placement.";
                responseComponent = (
                    <div className="mt-3 space-y-2">
                        <div className="flex items-center justify-between p-2.5 bg-rose-50 border border-rose-100 rounded-xl">
                            <div>
                                <h5 className="text-xs font-bold text-slate-800">Fortune Mustard Oil</h5>
                                <p className="text-[10px] text-slate-500">2 units left · Last batch Jan 2026</p>
                            </div>
                            <span className="px-2 py-0.5 rounded-full bg-rose-100 text-rose-700 text-[10px] font-extrabold uppercase">Critical</span>
                        </div>
                        <div className="flex items-center justify-between p-2.5 bg-amber-50 border border-amber-100 rounded-xl">
                            <div>
                                <h5 className="text-xs font-bold text-slate-800">Tata Salt Active</h5>
                                <p className="text-[10px] text-slate-500">5 units left · Last batch Feb 2026</p>
                            </div>
                            <span className="px-2 py-0.5 rounded-full bg-amber-100 text-amber-700 text-[10px] font-extrabold uppercase">Low</span>
                        </div>
                    </div>
                );
            } else if (text.toLowerCase().includes('collection') || text.toLowerCase().includes('owes') || text.toLowerCase().includes('money')) {
                responseText = "You have ₹18,400 outstanding across 3 active accounts. Reminders have been scheduled for Auto-Pilot dispatch.";
                responseComponent = (
                    <div className="mt-3 space-y-2">
                        <div className="flex justify-between items-center p-2.5 bg-slate-50 border border-slate-200 rounded-xl">
                            <div>
                                <p className="text-xs font-bold text-slate-800">Rajesh Kumar</p>
                                <p className="text-[10px] text-slate-500">₹8,200 due · Invoice #INV-882</p>
                            </div>
                            <button className="px-3 py-1 bg-emerald-600 hover:bg-emerald-700 text-white font-extrabold text-[10px] rounded-lg transition-all flex items-center gap-1 shadow-sm">
                                <Send size={10} /> Send WhatsApp
                            </button>
                        </div>
                        <div className="flex justify-between items-center p-2.5 bg-slate-50 border border-slate-200 rounded-xl">
                            <div>
                                <p className="text-xs font-bold text-slate-800">Amit Verma</p>
                                <p className="text-[10px] text-slate-500">₹6,000 due · Invoice #INV-865</p>
                            </div>
                            <span className="px-2 py-1 bg-slate-200 text-slate-600 font-extrabold text-[10px] rounded-lg">WhatsApp Read</span>
                        </div>
                    </div>
                );
            } else {
                responseText = "I processed your request, but I could not find a matching dashboard category. Try asking about 'profit margins', 'low stock items', or 'customer collections'.";
            }

            setChatMessages(prev => [...prev, { 
                sender: 'bot', 
                text: responseText, 
                component: responseComponent,
                timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) 
            }]);
            setIsTyping(false);
        }, 1000);
    };

    return (
        <div className="min-h-screen bg-[#FAFBFD] text-slate-800 font-sans selection:bg-blue-600 selection:text-white scroll-smooth overflow-x-hidden">
            
            {/* NOISE & GRADIENT BACKGROUND */}
            <div className="fixed inset-0 z-0 pointer-events-none opacity-[0.015]" style={{backgroundImage: 'url("data:image/svg+xml,%3Csvg viewBox=%220 0 200 200%22 xmlns=%22http://www.w3.org/2000/svg%22%3E%3Cfilter id=%22noiseFilter%22%3E%3CfeTurbulence type=%22fractalNoise%22 baseFrequency=%220.75%22 numOctaves=%223%22 stitchTiles=%22stitch%22/%3E%3C/filter%3E%3Crect width=%22100%25%22 height=%22100%25%22 filter=%22url(%23noiseFilter)%22/%3E%3C/svg%3E")'}}></div>
            <div className="fixed top-[-25%] left-[-15%] w-[60%] h-[60%] rounded-full bg-blue-500/10 blur-[130px] pointer-events-none z-0"></div>
            <div className="fixed bottom-[-20%] right-[-10%] w-[55%] h-[55%] rounded-full bg-purple-500/5 blur-[130px] pointer-events-none z-0"></div>
            <div className="fixed top-[40%] left-[20%] w-[50vh] h-[50vh] rounded-full bg-indigo-500/5 blur-[150px] pointer-events-none z-0"></div>

            {/* NAVBAR */}
            <nav className={`fixed top-0 w-full z-50 transition-all duration-300 ${scrolled ? 'bg-white/80 backdrop-blur-xl border-b border-slate-200/60 py-4 shadow-sm' : 'bg-transparent py-6'}`}>
                <div className="max-w-7xl mx-auto px-6 flex items-center justify-between">
                    <motion.div 
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        className="flex items-center gap-3 cursor-pointer animate-fade-in"
                        onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
                    >
                        <div className="relative">
                            <div className="absolute inset-0 bg-blue-600 blur-[8px] opacity-35 rounded-full" />
                            <img src={logo} alt="FinSathi" className="w-8 h-8 object-contain relative z-10 drop-shadow-md" />
                        </div>
                        <span className="text-xl font-black tracking-tight text-slate-900">FinSathi</span>
                    </motion.div>

                    <div className="hidden lg:flex items-center gap-7 bg-slate-100/60 border border-slate-200/80 px-8 py-2 rounded-full backdrop-blur-md">
                        {navLinks.map((link) => (
                            <button key={link.name} onClick={() => scrollToSection(link.href)} className="text-[11px] font-bold uppercase tracking-wider text-slate-600 hover:text-slate-900 transition-colors relative group">
                                {link.name}
                                <span className="absolute -bottom-1 left-0 w-0 h-[1.5px] bg-gradient-to-r from-blue-600 to-purple-600 transition-all group-hover:w-full"></span>
                            </button>
                        ))}
                    </div>

                    <div className="hidden lg:flex items-center gap-4">
                        {isLoggedIn ? (
                            <Link to="/dashboard" className="px-6 py-2 rounded-full bg-slate-900 hover:bg-slate-800 text-white font-bold text-xs transition-all shadow-sm flex items-center gap-2">
                                Open Dashboard <ArrowRight size={14} />
                            </Link>
                        ) : (
                            <>
                                <Link to="/login" className="px-4 py-2 text-xs font-bold uppercase tracking-wider text-slate-600 hover:text-slate-900 transition-colors">
                                    Sign In
                                </Link>
                                <Link to="/register" className="px-6 py-2.5 rounded-full bg-blue-600 text-white font-black text-xs hover:bg-blue-700 transition-all shadow-md shadow-blue-500/10">
                                    Get Started
                                </Link>
                            </>
                        )}
                    </div>

                    <button className="lg:hidden text-slate-800 relative z-50 p-2" onClick={() => setMobileMenuOpen(!mobileMenuOpen)}>
                        {mobileMenuOpen ? <X size={24} /> : <Menu size={24} />}
                    </button>
                </div>
            </nav>

            {/* MOBILE MENU */}
            <AnimatePresence>
                {mobileMenuOpen && (
                    <motion.div 
                        initial={{ opacity: 0, y: -20 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, y: -20 }}
                        className="fixed inset-0 z-45 bg-[#FAFBFD]/98 backdrop-blur-xl flex flex-col items-center justify-center gap-8 px-6"
                    >
                        {navLinks.map((link) => (
                            <button key={link.name} onClick={() => scrollToSection(link.href)} className="text-lg font-bold text-slate-800 hover:text-blue-600">
                                {link.name}
                            </button>
                        ))}
                        <div className="flex flex-col w-full max-w-xs gap-4 mt-8">
                            {isLoggedIn ? (
                                <Link to="/dashboard" onClick={() => setMobileMenuOpen(false)} className="w-full py-3 rounded-xl bg-slate-900 text-white text-center font-black">Open Dashboard</Link>
                            ) : (
                                <>
                                    <Link to="/login" onClick={() => setMobileMenuOpen(false)} className="w-full py-3 rounded-xl border border-slate-200 text-center font-bold text-slate-700 bg-white">Log In</Link>
                                    <Link to="/register" onClick={() => setMobileMenuOpen(false)} className="w-full py-3 rounded-xl bg-blue-600 text-white text-center font-black shadow-lg">Get Started</Link>
                                </>
                            )}
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>

            {/* HERO SECTION */}
            <section className="relative pt-44 pb-20 px-6 flex flex-col items-center justify-center min-h-[80vh] z-10 text-center">
                <motion.div 
                    initial={{ opacity: 0, scale: 0.95 }} 
                    animate={{ opacity: 1, scale: 1 }} 
                    className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-blue-50 border border-blue-100 text-blue-700 text-[10px] font-bold uppercase tracking-widest mb-6 shadow-sm"
                >
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse"></span> Intelligent OS for Indian MSMEs
                </motion.div>

                <motion.h1 
                    initial={{ opacity: 0, y: 20 }} 
                    animate={{ opacity: 1, y: 0 }} 
                    transition={{ duration: 0.6 }} 
                    className="text-4xl sm:text-6xl md:text-7xl lg:text-[76px] font-black tracking-tight leading-[1.08] mb-8 text-slate-900 max-w-5xl"
                >
                    Command your business.<br />
                    <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 via-indigo-600 to-purple-600 drop-shadow-sm">Automate your cash flow.</span>
                </motion.h1>

                <motion.p 
                    initial={{ opacity: 0, y: 20 }} 
                    animate={{ opacity: 1, y: 0 }} 
                    transition={{ duration: 0.6, delay: 0.1 }} 
                    className="text-sm sm:text-base md:text-lg text-slate-500 max-w-2xl mb-12 font-medium leading-relaxed"
                >
                    FinSathi integrates high-speed POS billing, dynamic batch inventory pricing, automatic WhatsApp reminders, and eligibility calculations for Indian government grants into one premium workspace.
                </motion.p>

                <motion.div 
                    initial={{ opacity: 0, y: 20 }} 
                    animate={{ opacity: 1, y: 0 }} 
                    transition={{ duration: 0.6, delay: 0.2 }} 
                    className="flex flex-col sm:flex-row items-center gap-4 w-full sm:w-auto"
                >
                    <Link to="/register" className="w-full sm:w-auto px-8 py-3.5 bg-slate-900 hover:bg-slate-800 text-white font-extrabold rounded-full transition-all flex items-center justify-center gap-2 text-sm shadow-[0_10px_25px_-5px_rgba(15,23,42,0.15)]">
                        Launch Your Workspace <ArrowUpRight size={16} />
                    </Link>
                    <button onClick={() => scrollToSection('#demo')} className="w-full sm:w-auto px-8 py-3.5 bg-white text-slate-800 border border-slate-200 font-bold rounded-full hover:bg-slate-50 transition-all text-sm shadow-sm">
                        Interactive Demo
                    </button>
                </motion.div>
                
                {/* Scroll Indicator */}
                <motion.div 
                    initial={{ opacity: 0 }} 
                    animate={{ opacity: 1 }} 
                    transition={{ delay: 1 }} 
                    className="absolute bottom-4 left-1/2 -translate-x-1/2 flex flex-col items-center gap-2 text-slate-400 cursor-pointer hover:text-slate-600 transition-colors"
                    onClick={() => scrollToSection('#demo')}
                >
                    <span className="text-[9px] uppercase tracking-widest font-bold">Scroll to interactive demo</span>
                    <ChevronDown size={14} className="animate-bounce" />
                </motion.div>
            </section>

            {/* INTERACTIVE DEMO (MOCKUP WORKSPACE) */}
            <section id="demo" className="py-24 px-6 relative z-10 max-w-[1240px] mx-auto border-t border-slate-200/60">
                <div className="text-center mb-16">
                    <h2 className="text-xs font-bold uppercase tracking-widest text-blue-600 mb-3">Live Simulation</h2>
                    <h3 className="text-2xl sm:text-4xl font-black text-slate-900 mb-4 font-sans tracking-tight">Feel the premium speed.</h3>
                    <p className="text-slate-500 max-w-xl mx-auto text-xs sm:text-sm leading-relaxed">Click through the simulator below to experience our core cash intelligence modules.</p>
                </div>

                <div className="relative rounded-[2rem] border border-slate-200/80 bg-white p-3 shadow-[0_20px_50px_rgba(0,0,0,0.05)]">
                    <div className="absolute inset-0 bg-gradient-to-tr from-blue-500/5 via-transparent to-purple-500/5 rounded-[2rem] pointer-events-none"></div>
                    
                    {/* Mockup Frame */}
                    <div className="rounded-[1.5rem] overflow-hidden border border-slate-200/60 bg-[#F8FAFC] grid grid-cols-12 min-h-[580px] text-left">
                        
                        {/* Sidebar Mock (Classic Premium Dark Sidebar + Light Page Content) */}
                        <div className="col-span-3 hidden md:flex flex-col border-r border-slate-800 bg-[#0F172A] p-4 justify-between select-none">
                            <div className="space-y-6">
                                {/* Title block */}
                                <div className="flex items-center gap-2.5 px-2">
                                    <img src={logo} alt="FinSathi logo" className="w-6 h-6 object-contain filter brightness-0 invert" style={{filter: 'brightness(0) invert(1)'}} />
                                    <span className="font-extrabold text-sm text-white">FinSathi</span>
                                    <span className="px-1.5 py-0.5 rounded bg-blue-500/25 text-blue-300 text-[8px] font-bold">v2.0</span>
                                </div>

                                {/* Nav Links list */}
                                <nav className="space-y-1">
                                    <div className={`flex items-center gap-2.5 px-3 py-2 rounded-lg text-xs font-semibold cursor-pointer transition-colors ${activeTab === 'overview' ? 'bg-white/5 text-white' : 'text-slate-400 hover:text-slate-200'}`} onClick={() => setActiveTab('overview')}>
                                        <BarChart2 size={14} /> Dashboard Overview
                                    </div>
                                    <div className={`flex items-center gap-2.5 px-3 py-2 rounded-lg text-xs font-semibold cursor-pointer transition-colors ${activeTab === 'ai' ? 'bg-white/5 text-white' : 'text-slate-400 hover:text-slate-200'}`} onClick={() => setActiveTab('ai')}>
                                        <Cpu size={14} /> FinVoice AI Assistant
                                    </div>
                                    <div className={`flex items-center gap-2.5 px-3 py-2 rounded-lg text-xs font-semibold cursor-pointer transition-colors ${activeTab === 'cashflow' ? 'bg-white/5 text-white' : 'text-slate-400 hover:text-slate-200'}`} onClick={() => setActiveTab('cashflow')}>
                                        <Activity size={14} /> Cash Flow Forecast
                                    </div>
                                    <div className="flex items-center gap-2.5 px-3 py-2 rounded-lg text-xs font-semibold text-slate-600 hover:text-slate-500 cursor-not-allowed">
                                        <Zap size={14} /> POS Invoicing
                                    </div>
                                    <div className="flex items-center gap-2.5 px-3 py-2 rounded-lg text-xs font-semibold text-slate-600 hover:text-slate-500 cursor-not-allowed">
                                        <Layers size={14} /> Inventory Batches
                                    </div>
                                    <div className="flex items-center gap-2.5 px-3 py-2 rounded-lg text-xs font-semibold text-slate-600 hover:text-slate-500 cursor-not-allowed">
                                        <Users size={14} /> Staff Attendance
                                    </div>
                                </nav>
                            </div>

                            {/* Plan Usage */}
                            <div className="p-3 bg-white/[0.03] border border-white/5 rounded-xl space-y-2">
                                <div className="flex justify-between text-[10px] font-bold text-slate-400">
                                    <span>MONTHLY INVOICES</span>
                                    <span>12 / 100</span>
                                </div>
                                <div className="h-1.5 w-full bg-white/10 rounded-full overflow-hidden">
                                    <div className="h-full w-[12%] bg-blue-500 rounded-full" />
                                </div>
                                <p className="text-[9px] text-slate-500 font-medium">Resetting in 14 days · Free tier</p>
                            </div>
                        </div>

                        {/* Main Screen Mock */}
                        <div className="col-span-12 md:col-span-9 flex flex-col bg-[#F8FAFC]">
                            {/* Mock Header */}
                            <header className="flex items-center justify-between px-6 py-4 border-b border-slate-200/60 bg-white">
                                <div className="flex items-center gap-3">
                                    {/* Mobile Menu Icon */}
                                    <div className="md:hidden p-1 text-slate-500">
                                        <Menu size={16} />
                                    </div>
                                    <span className="text-xs font-bold text-slate-500">Workspace</span>
                                    <span className="text-slate-300">/</span>
                                    <span className="text-xs font-bold text-slate-800 capitalize">{activeTab === 'overview' ? 'Dashboard Overview' : activeTab === 'ai' ? 'FinVoice AI Assistant' : 'Cash Flow Forecast'}</span>
                                </div>
                                <div className="flex items-center gap-4">
                                    <div className="hidden sm:flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-50 border border-slate-200/80 text-[10px] font-semibold text-slate-500">
                                        <Search size={10} /> Search command... <kbd className="text-[8px] bg-slate-200 px-1 rounded text-slate-600 ml-2">⌘K</kbd>
                                    </div>
                                    <div className="flex items-center gap-1.5">
                                        <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-ping"></span>
                                        <span className="text-[10px] font-bold text-emerald-600 uppercase tracking-wider">Sync Active</span>
                                    </div>
                                </div>
                            </header>

                            {/* Screen Body */}
                            <div className="p-6 flex-1 overflow-y-auto max-h-[500px]">
                                
                                {/* 🔴 TAB CONTENT: OVERVIEW */}
                                {activeTab === 'overview' && (
                                    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-6">
                                        
                                        {/* Metric Cards Row */}
                                        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                                            <div className="p-4 rounded-xl bg-white border border-slate-200/60 shadow-sm space-y-1">
                                                <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Daily Revenues</p>
                                                <div className="flex items-baseline justify-between">
                                                    <h4 className="text-xl font-black text-slate-900">₹48,250</h4>
                                                    <span className="text-[10px] text-emerald-700 font-bold bg-emerald-50 border border-emerald-100 px-1.5 py-0.5 rounded">+12.4%</span>
                                                </div>
                                                <div className="h-6 w-full pt-1.5 opacity-80">
                                                    <svg viewBox="0 0 100 20" className="w-full h-full text-emerald-500 overflow-visible">
                                                        <path d="M 0 18 Q 20 12 40 14 T 80 5 T 100 8" fill="none" stroke="currentColor" strokeWidth={1.5} />
                                                        <path d="M 0 18 Q 20 12 40 14 T 80 5 T 100 8 L 100 20 L 0 20 Z" fill="currentColor" fillOpacity={0.05} />
                                                    </svg>
                                                </div>
                                            </div>

                                            <div className="p-4 rounded-xl bg-white border border-slate-200/60 shadow-sm flex items-center justify-between">
                                                <div className="space-y-1">
                                                    <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">AI Health Score</p>
                                                    <h4 className="text-xl font-black text-slate-900">94/100</h4>
                                                    <p className="text-[9px] text-emerald-600 font-bold">Excellent cash flow</p>
                                                </div>
                                                <div className="relative w-12 h-12">
                                                    <svg className="w-full h-full -rotate-95" viewBox="0 0 36 36">
                                                        <path className="text-slate-100" stroke="currentColor" strokeWidth="3" fill="none" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
                                                        <path className="text-blue-600 drop-shadow-sm" strokeDasharray="94, 100" strokeLinecap="round" stroke="currentColor" strokeWidth="3" fill="none" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
                                                    </svg>
                                                    <span className="absolute inset-0 flex items-center justify-center text-[10px] font-black text-slate-800">94%</span>
                                                </div>
                                            </div>

                                            <div className="p-4 rounded-xl bg-white border border-slate-200/60 shadow-sm space-y-1">
                                                <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">FinPredict Outlook</p>
                                                <h4 className="text-xl font-black text-slate-900 flex items-center gap-1.5">
                                                    <Check className="text-indigo-600" size={18} /> Healthy
                                                </h4>
                                                <p className="text-[9px] text-slate-500 font-medium">14-day cash buffer secured</p>
                                                <div className="h-6 w-full pt-1.5 opacity-80">
                                                    <svg viewBox="0 0 100 20" className="w-full h-full text-indigo-500 overflow-visible">
                                                        <path d="M 0 15 L 10 15 L 20 14 L 30 14 L 40 14 L 50 15 L 60 12 L 70 12 L 80 10 L 90 10 L 100 9" fill="none" stroke="currentColor" strokeWidth={1.5} strokeDasharray="1.5 1.5" />
                                                    </svg>
                                                </div>
                                            </div>
                                        </div>

                                        {/* Main Sales Analytics Graph Mockup */}
                                        <div className="p-5 rounded-2xl bg-white border border-slate-200/60 shadow-sm">
                                            <div className="flex justify-between items-center mb-4">
                                                <div>
                                                    <h5 className="text-xs font-extrabold text-slate-900 uppercase tracking-wider">7-Day Sales vs Expense Trends</h5>
                                                    <p className="text-[9px] text-slate-400">Live operational ledger logs</p>
                                                </div>
                                                <div className="flex items-center gap-3 text-[10px] font-bold text-slate-500">
                                                    <span className="flex items-center gap-1"><span className="w-2 h-2 rounded bg-blue-500"></span> Sales</span>
                                                    <span className="flex items-center gap-1"><span className="w-2 h-2 rounded bg-purple-500"></span> Expenses</span>
                                                </div>
                                            </div>
                                            
                                            <div 
                                                className="h-44 relative w-full border-b border-slate-200 border-l border-slate-200"
                                                onMouseEnter={() => setChartHovered(true)}
                                                onMouseLeave={() => setChartHovered(false)}
                                            >
                                                {/* Gradient Area SVGs */}
                                                <svg viewBox="0 0 500 150" className="w-full h-full overflow-visible pointer-events-none">
                                                    <defs>
                                                        <linearGradient id="demoSalesGrad" x1="0" y1="0" x2="0" y2="1">
                                                            <stop offset="0%" stopColor="#3B82F6" stopOpacity={0.2} />
                                                            <stop offset="100%" stopColor="#3B82F6" stopOpacity={0} />
                                                        </linearGradient>
                                                        <linearGradient id="demoExpGrad" x1="0" y1="0" x2="0" y2="1">
                                                            <stop offset="0%" stopColor="#8B5CF6" stopOpacity={0.12} />
                                                            <stop offset="100%" stopColor="#8B5CF6" stopOpacity={0} />
                                                        </linearGradient>
                                                    </defs>
                                                    {/* grid lines */}
                                                    <line x1="0" y1="30" x2="500" y2="30" stroke="rgba(0,0,0,0.03)" strokeDasharray="3" />
                                                    <line x1="0" y1="75" x2="500" y2="75" stroke="rgba(0,0,0,0.03)" strokeDasharray="3" />
                                                    <line x1="0" y1="120" x2="500" y2="120" stroke="rgba(0,0,0,0.03)" strokeDasharray="3" />
                                                    
                                                    {/* Expenses Area */}
                                                    <path d="M 0 130 Q 80 120 160 85 T 320 95 T 480 70 L 500 70 L 500 150 L 0 150 Z" fill="url(#demoExpGrad)" />
                                                    <path d="M 0 130 Q 80 120 160 85 T 320 95 T 480 70 L 500 70" fill="none" stroke="#8B5CF6" strokeWidth={1.5} />

                                                    {/* Sales Area */}
                                                    <path d="M 0 110 Q 80 75 160 50 T 320 35 T 480 20 L 500 20 L 500 150 L 0 150 Z" fill="url(#demoSalesGrad)" />
                                                    <path d="M 0 110 Q 80 75 160 50 T 320 35 T 480 20 L 500 20" fill="none" stroke="#3B82F6" strokeWidth={2} />

                                                    {/* Dots */}
                                                    <circle cx="160" cy="50" r="3.5" fill="#3B82F6" className="animate-pulse" />
                                                    <circle cx="320" cy="35" r="3.5" fill="#3B82F6" />
                                                    <circle cx="480" cy="20" r="3.5" fill="#3B82F6" />
                                                    
                                                    {/* Hover tracker line */}
                                                    {chartHovered && (
                                                        <>
                                                            <line x1="320" y1="0" x2="320" y2="150" stroke="#3B82F6" strokeWidth={1} strokeDasharray="2" />
                                                            <circle cx="320" cy="35" r="5.5" fill="#FFFFFF" stroke="#3B82F6" strokeWidth={2} />
                                                        </>
                                                    )}
                                                </svg>

                                                {/* Tooltip Overlay */}
                                                {chartHovered && (
                                                    <div className="absolute top-2 left-[335px] p-2 bg-slate-900 border border-slate-800 rounded-lg text-[9px] text-white shadow-lg space-y-0.5 z-10 pointer-events-none animate-fade-in">
                                                        <p className="font-extrabold uppercase text-slate-400">{chartHoverData.day}</p>
                                                        <p>Sales: <span className="font-mono text-emerald-400">{chartHoverData.sales}</span></p>
                                                        <p>Margins: <span className="font-mono text-blue-400">{chartHoverData.margin}</span></p>
                                                    </div>
                                                )}
                                            </div>
                                            
                                            {/* Axis labels */}
                                            <div className="flex justify-between text-[8px] font-bold text-slate-400 mt-2 px-1">
                                                <span>Mon</span>
                                                <span>Tue</span>
                                                <span>Wed</span>
                                                <span>Thu</span>
                                                <span>Fri (Today)</span>
                                                <span>Sat</span>
                                                <span>Sun</span>
                                            </div>
                                        </div>

                                        {/* Invoices Feed Mock */}
                                        <div className="space-y-3">
                                            <h6 className="text-[10px] font-extrabold text-slate-800 uppercase tracking-wider">Recent Transactions</h6>
                                            <div className="border border-slate-200/80 bg-white rounded-xl overflow-hidden text-xs shadow-sm">
                                                <div className="grid grid-cols-12 bg-slate-50 border-b border-slate-100 p-2.5 font-bold text-slate-400 text-[10px] uppercase">
                                                    <span className="col-span-4">Customer</span>
                                                    <span className="col-span-3">Date</span>
                                                    <span className="col-span-2 text-right">Total</span>
                                                    <span className="col-span-3 text-right">Status</span>
                                                </div>
                                                <div className="grid grid-cols-12 p-2.5 border-b border-slate-100 items-center text-slate-600 hover:bg-slate-50 transition-colors">
                                                    <span className="col-span-4 font-bold text-slate-800">Rajesh Kumar</span>
                                                    <span className="col-span-3 text-[10px] text-slate-400">Today · 10:14 AM</span>
                                                    <span className="col-span-2 text-right font-mono text-slate-700">₹8,200</span>
                                                    <span className="col-span-3 text-right flex justify-end gap-1.5 items-center">
                                                        <span className="px-1.5 py-0.5 rounded bg-rose-50 text-rose-700 text-[8px] font-black uppercase border border-rose-100">Unpaid</span>
                                                        <span className="text-[8px] text-slate-400 font-medium">Sent</span>
                                                    </span>
                                                </div>
                                                <div className="grid grid-cols-12 p-2.5 items-center text-slate-600 hover:bg-slate-50 transition-colors">
                                                    <span className="col-span-4 font-bold text-slate-800">Shreya Gupta</span>
                                                    <span className="col-span-3 text-[10px] text-slate-400">Today · 09:44 AM</span>
                                                    <span className="col-span-2 text-right font-mono text-slate-700">₹4,850</span>
                                                    <span className="col-span-3 text-right flex justify-end gap-1.5 items-center">
                                                        <span className="px-1.5 py-0.5 rounded bg-emerald-50 text-emerald-700 text-[8px] font-black uppercase border border-emerald-100">Paid</span>
                                                        <span className="text-[8px] text-blue-600 font-bold">Read</span>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </motion.div>
                                )}

                                {/* 🔵 TAB CONTENT: FINVOICE AI */}
                                {activeTab === 'ai' && (
                                    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-4 flex flex-col h-[400px] justify-between">
                                        
                                        {/* Chat History Panel */}
                                        <div className="flex-1 overflow-y-auto space-y-3 pr-2 scrollbar-thin">
                                            {chatMessages.map((msg, i) => (
                                                <div key={i} className={`flex flex-col ${msg.sender === 'user' ? 'items-end' : 'items-start'}`}>
                                                    <div className={`max-w-[80%] rounded-2xl px-4 py-2.5 text-xs ${msg.sender === 'user' ? 'bg-blue-600 text-white rounded-br-none shadow-sm' : 'bg-white text-slate-800 border border-slate-200 shadow-sm rounded-bl-none'}`}>
                                                        <p className="leading-relaxed font-semibold">{msg.text}</p>
                                                        {msg.component}
                                                    </div>
                                                    <span className="text-[8px] text-slate-400 mt-1 font-mono">{msg.timestamp}</span>
                                                </div>
                                            ))}

                                            {isTyping && (
                                                <div className="flex items-center gap-2 p-3 bg-white border border-slate-200 rounded-2xl max-w-xs shadow-sm">
                                                    <span className="w-1.5 h-1.5 rounded-full bg-slate-400 animate-bounce" style={{ animationDelay: '0ms' }} />
                                                    <span className="w-1.5 h-1.5 rounded-full bg-slate-400 animate-bounce" style={{ animationDelay: '150ms' }} />
                                                    <span className="w-1.5 h-1.5 rounded-full bg-slate-400 animate-bounce" style={{ animationDelay: '300ms' }} />
                                                    <span className="text-[10px] text-slate-500 font-bold uppercase tracking-wider ml-1">FinVoice is searching...</span>
                                                </div>
                                            )}
                                        </div>

                                        {/* Suggestions & Input Block */}
                                        <div className="space-y-3 pt-3 border-t border-slate-200">
                                            <div className="flex flex-wrap gap-2">
                                                {chatSuggestions.map((sug, i) => (
                                                    <button key={i} className="px-2.5 py-1 rounded-full bg-white hover:bg-slate-50 border border-slate-200 text-[9px] font-bold text-slate-600 transition-colors uppercase tracking-wider shadow-sm" onClick={() => handleSendChat(sug.query)}>
                                                        {sug.label}
                                                    </button>
                                                ))}
                                            </div>

                                            <div className="flex gap-2">
                                                <input 
                                                    type="text" 
                                                    className="flex-1 px-4 py-2.5 rounded-xl bg-white border border-slate-200 focus:border-blue-500 focus:outline-none text-xs text-slate-800 placeholder-slate-400 font-medium shadow-sm" 
                                                    placeholder="Ask in Hindi, Hinglish or English..." 
                                                    value={chatQuery}
                                                    onChange={e => setChatQuery(e.target.value)}
                                                    onKeyDown={e => e.key === 'Enter' && handleSendChat()}
                                                />
                                                <button className="p-2.5 bg-slate-900 text-white hover:bg-slate-800 transition-all rounded-xl flex items-center justify-center shadow-sm" onClick={() => handleSendChat()}>
                                                    <Send size={14} />
                                                </button>
                                            </div>
                                        </div>
                                    </motion.div>
                                )}

                                {/* 🔵 TAB CONTENT: CASH FLOW FORECAST */}
                                {activeTab === 'cashflow' && (
                                    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-6">
                                        
                                        {/* Alert Header */}
                                        <div className="p-4 rounded-xl bg-indigo-50 border border-indigo-100 flex gap-3.5 items-start">
                                            <div className="p-2 rounded-lg bg-indigo-100 text-indigo-600">
                                                <Info size={16} />
                                            </div>
                                            <div>
                                                <h5 className="text-xs font-black text-indigo-900">No Cash Crunch Projected</h5>
                                                <p className="text-[10px] text-indigo-700 leading-relaxed mt-1">Based on the moving average of daily revenues (₹24,800/day) and pending receivables, your ledger balance is projected to remain healthy. Next major payout is Staff Payroll in 7 days (₹42,000).</p>
                                            </div>
                                        </div>

                                        {/* Sparkline grid */}
                                        <div className="p-5 rounded-2xl bg-white border border-slate-200/60 shadow-sm space-y-4">
                                            <div className="flex justify-between items-center">
                                                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">14-Day Forecast Balance Map</span>
                                                <span className="text-[9px] font-mono text-slate-400 font-medium">Updated 10m ago</span>
                                            </div>

                                            <div className="h-32 flex items-end justify-between gap-1.5 pt-4">
                                                {/* Simulated 14 bars */}
                                                {[85, 90, 80, 75, 70, 78, 92, 100, 95, 90, 85, 80, 84, 88].map((val, idx) => (
                                                    <div key={idx} className="flex-1 flex flex-col items-center gap-2 group cursor-pointer">
                                                        <div className="w-full relative rounded-t bg-indigo-100 group-hover:bg-indigo-200 transition-colors" style={{ height: `${val}%` }}>
                                                            <div className="absolute top-0 left-0 w-full h-1 bg-indigo-500 rounded-t" />
                                                        </div>
                                                        <span className="text-[8px] font-bold text-slate-400">{idx + 1}</span>
                                                    </div>
                                                ))}
                                            </div>
                                            <div className="flex justify-between text-[8px] font-bold text-slate-400 uppercase">
                                                <span>Today (June 23)</span>
                                                <span>July 6</span>
                                            </div>
                                        </div>

                                        {/* Breakdown table */}
                                        <div className="grid grid-cols-2 gap-4">
                                            <div className="p-3 bg-white border border-slate-200/60 shadow-sm rounded-xl">
                                                <p className="text-[9px] font-bold text-slate-400 uppercase">Est. Total Inflows (14d)</p>
                                                <p className="text-sm font-black text-emerald-600 mt-1 font-mono">+₹3,47,200</p>
                                                <p className="text-[8px] text-slate-500 mt-0.5">Average collection velocity 4.2d</p>
                                            </div>
                                            <div className="p-3 bg-white border border-slate-200/60 shadow-sm rounded-xl">
                                                <p className="text-[9px] font-bold text-slate-400 uppercase">Est. Total Outflows (14d)</p>
                                                <p className="text-sm font-black text-rose-600 mt-1 font-mono">-₹1,14,000</p>
                                                <p className="text-[8px] text-slate-500 mt-0.5">Supplier bills + staff payroll</p>
                                            </div>
                                        </div>
                                    </motion.div>
                                )}

                            </div>
                        </div>

                    </div>
                </div>
            </section>

            {/* v2.0 FEATURES GRID */}
            <section id="features" className="py-32 relative z-10 border-t border-slate-200/60 bg-white">
                <div className="max-w-7xl mx-auto px-6">
                    <div className="text-center mb-24">
                        <h2 className="text-xs font-bold uppercase tracking-widest text-blue-600 mb-4">Enterprise Capabilities</h2>
                        <h3 className="text-3xl sm:text-4xl font-black text-slate-900 mb-6 tracking-tight">Redefined for maximum efficiency.</h3>
                        <p className="text-slate-500 max-w-2xl mx-auto text-sm sm:text-base leading-relaxed">
                            FinSathi wraps complex database structures, external APIs, and local computations into a clean, modern SaaS operating interface.
                        </p>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                        <FeatureBox 
                            icon={Cpu} 
                            title="FinVoice AI Assistant" 
                            desc="Speak or type in English, Hindi, or Hinglish. Instantly generate profit breakdowns, identify critical anomalies, or review sales metrics using Gemini AI intents." 
                            delay={0.1} 
                        />
                        <FeatureBox 
                            icon={Activity} 
                            title="FinPredict Cash Forecast" 
                            desc="14-day forward cash flow balance projection engine. Scans supplier dues and invoice settlement velocities to trigger automated cash crunch warning notifications." 
                            delay={0.2} 
                        />
                        <FeatureBox 
                            icon={MessageSquare} 
                            title="WhatsApp Commerce" 
                            desc="Pre-configured Meta Graph API routes. Dispatch automated payment reminders with one-click links and monitor delivery milestones (Delivered/Read/Failed)." 
                            delay={0.3} 
                        />
                        <FeatureBox 
                            icon={Layers} 
                            title="Digital Catalog Links" 
                            desc="Instantly publish a customer-facing public storefront linked to your live inventory. Capture order submissions directly into your local database." 
                            delay={0.4} 
                        />
                        <FeatureBox 
                            icon={Award} 
                            title="Subsidy Matchmaker" 
                            desc="Search Indian government MSME subsidies (Mudra, PMEGP). Our matching engine computes your tax profile, business category, and assets to show eligibility scores." 
                            delay={0.5} 
                        />
                        <FeatureBox 
                            icon={Zap} 
                            title="5-Second POS Terminal" 
                            desc="Lightning-fast digital billing checkout. Auto-decrement stock counts, calculate dynamic split GST, apply safe discount thresholds, and print invoice PDFs." 
                            delay={0.6} 
                        />
                    </div>
                </div>
            </section>

            {/* GOVERNMENT SUBSIDY SPOTLIGHT SECTION */}
            <section id="subsidy" className="py-28 relative z-10 bg-[#F8FAFC] border-t border-b border-slate-200/60">
                <div className="max-w-7xl mx-auto px-6">
                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
                        <div className="space-y-6">
                            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-55 border border-emerald-100 text-emerald-700 text-[10px] font-bold uppercase tracking-wider">
                                Growth Intelligence
                            </div>
                            <h3 className="text-3xl sm:text-4xl font-black text-slate-900 leading-tight tracking-tight">Unlock government subsidies without the paperwork hassle.</h3>
                            <p className="text-slate-500 text-sm sm:text-base leading-relaxed">
                                Small businesses lose crores in government schemes due to complex applications and eligibility rules. FinSathi monitors your profile criteria against active scheme parameters to show matching scores in real-time.
                            </p>
                            
                            <ul className="space-y-3.5 text-xs sm:text-sm font-semibold text-slate-600">
                                <li className="flex items-center gap-2.5">
                                    <span className="w-5 h-5 rounded-full bg-emerald-100 text-emerald-750 flex items-center justify-center"><Check size={12} /></span>
                                    Instant matching for Mudra Loans (Shishu, Kishor, Tarun tiers)
                                </li>
                                <li className="flex items-center gap-2.5">
                                    <span className="w-5 h-5 rounded-full bg-emerald-100 text-emerald-750 flex items-center justify-center"><Check size={12} /></span>
                                    Prime Minister's Employment Generation Programme (PMEGP) eligibility
                                </li>
                                <li className="flex items-center gap-2.5">
                                    <span className="w-5 h-5 rounded-full bg-emerald-100 text-emerald-750 flex items-center justify-center"><Check size={12} /></span>
                                    Automatic computation of Category (General/OBC/SC/ST) and Location parameters
                                </li>
                            </ul>

                            <div className="pt-4">
                                <Link to="/register" className="inline-flex items-center gap-2 px-6 py-3 bg-slate-900 hover:bg-slate-800 text-white font-extrabold text-xs uppercase tracking-wider rounded-full transition-all shadow-sm">
                                    Check Eligibility Free <ArrowRight size={14} />
                                </Link>
                            </div>
                        </div>

                        {/* Visual Mockup widget */}
                        <div className="relative">
                            <div className="absolute inset-0 bg-blue-500/5 blur-[80px] rounded-full" />
                            <div className="relative rounded-3xl border border-slate-200/80 bg-white p-8 shadow-xl space-y-6">
                                <div className="flex justify-between items-center border-b border-slate-100 pb-4">
                                    <div>
                                        <h4 className="text-sm font-bold text-slate-900">Government Scheme Matcher</h4>
                                        <p className="text-[10px] text-slate-400">Active matching profile: Retail Enterprise</p>
                                    </div>
                                    <span className="px-2 py-0.5 rounded-full bg-blue-50 border border-blue-100 text-blue-600 text-[9px] font-black uppercase">Live scan</span>
                                </div>

                                <div className="flex items-center gap-6 p-4 rounded-2xl bg-slate-50 border border-slate-200/60">
                                    {/* Circular Progress SVG */}
                                    <div className="relative w-16 h-16 shrink-0">
                                        <svg className="w-full h-full -rotate-90" viewBox="0 0 36 36">
                                            <circle className="text-slate-200" stroke="currentColor" strokeWidth="3" fill="none" cx="18" cy="18" r="16" />
                                            <circle className="text-emerald-500 drop-shadow-sm" strokeDasharray="88, 100" strokeLinecap="round" stroke="currentColor" strokeWidth="3" fill="none" cx="18" cy="18" r="16" />
                                        </svg>
                                        <span className="absolute inset-0 flex items-center justify-center text-xs font-black text-slate-800">88%</span>
                                    </div>
                                    <div>
                                        <h5 className="text-xs font-bold text-slate-900">Mudra Loan (Shishu Scheme)</h5>
                                        <p className="text-[10px] text-slate-500 leading-relaxed mt-1">Excellent eligibility. Criteria matched: Retail Category, Urban Location, and machinery equipment asset size.</p>
                                    </div>
                                </div>

                                <div className="space-y-2">
                                    <div className="flex justify-between items-center text-xs p-3 bg-slate-50 border border-slate-200/60 rounded-xl">
                                        <span className="text-slate-500 font-medium">Eligible Credit</span>
                                        <span className="font-mono font-bold text-slate-800">₹50,000 - ₹5,00,000</span>
                                    </div>
                                    <div className="flex justify-between items-center text-xs p-3 bg-slate-50 border border-slate-200/60 rounded-xl">
                                        <span className="text-slate-500 font-medium">Interest Subsidy</span>
                                        <span className="font-mono font-bold text-emerald-600">4.5% p.a. discount</span>
                                    </div>
                                </div>

                                <button className="w-full py-3 rounded-xl bg-slate-900 hover:bg-slate-800 font-bold text-xs uppercase tracking-wider text-white shadow-sm">
                                    Generate Mudra Proposal
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* WORKFLOW TIMELINE STEPPER */}
            <section id="how-it-works" className="py-32 relative z-10 bg-white">
                <div className="max-w-7xl mx-auto px-6">
                    <div className="flex flex-col lg:flex-row gap-16 items-center">
                        <div className="lg:w-1/2 space-y-8">
                            <div>
                                <h2 className="text-xs font-bold uppercase tracking-widest text-purple-600 mb-3">Workflow Architecture</h2>
                                <h3 className="text-3xl sm:text-4xl font-black text-slate-900 mb-6 tracking-tight font-sans">Launch operations in three phases.</h3>
                                <p className="text-slate-500 text-sm sm:text-base leading-relaxed">
                                    Put scattered spreadsheets behind you. Set up your ledger rules, run daily invoices, and let AI forecast margins automatically.
                                </p>
                            </div>
                            
                            <div className="space-y-4">
                                <button 
                                    className={`w-full text-left p-4 rounded-2xl border transition-all flex items-start gap-4 ${activeStep === 0 ? 'bg-slate-50 border-slate-200 shadow-sm' : 'bg-transparent border-transparent opacity-60 hover:opacity-85'}`}
                                    onClick={() => setActiveStep(0)}
                                >
                                    <span className={`w-7 h-7 rounded-full shrink-0 flex items-center justify-center text-xs font-bold ${activeStep === 0 ? 'bg-slate-950 text-white' : 'bg-slate-100 text-slate-600'}`}>01</span>
                                    <div>
                                        <h4 className="text-sm font-bold text-slate-900">Register & Customize Profile</h4>
                                        <p className="text-xs text-slate-500 leading-relaxed mt-1">Configure your tax ID (GSTIN), custom payment UPI handles, and default checkout invoice terms.</p>
                                    </div>
                                </button>

                                <button 
                                    className={`w-full text-left p-4 rounded-2xl border transition-all flex items-start gap-4 ${activeStep === 1 ? 'bg-slate-50 border-slate-200 shadow-sm' : 'bg-transparent border-transparent opacity-60 hover:opacity-85'}`}
                                    onClick={() => setActiveStep(1)}
                                >
                                    <span className={`w-7 h-7 rounded-full shrink-0 flex items-center justify-center text-xs font-bold ${activeStep === 1 ? 'bg-slate-950 text-white' : 'bg-slate-100 text-slate-600'}`}>02</span>
                                    <div>
                                        <h4 className="text-sm font-bold text-slate-900">Log Transactions & POS Billing</h4>
                                        <p className="text-xs text-slate-500 leading-relaxed mt-1">Process daily sales checkout items. Log operational expenses (including automated payroll runs).</p>
                                    </div>
                                </button>

                                <button 
                                    className={`w-full text-left p-4 rounded-2xl border transition-all flex items-start gap-4 ${activeStep === 2 ? 'bg-slate-50 border-slate-200 shadow-sm' : 'bg-transparent border-transparent opacity-60 hover:opacity-85'}`}
                                    onClick={() => setActiveStep(2)}
                                >
                                    <span className={`w-7 h-7 rounded-full shrink-0 flex items-center justify-center text-xs font-bold ${activeStep === 2 ? 'bg-slate-950 text-white' : 'bg-slate-100 text-slate-600'}`}>03</span>
                                    <div>
                                        <h4 className="text-sm font-bold text-slate-900">Analyze & Automate Reminders</h4>
                                        <p className="text-xs text-slate-500 leading-relaxed mt-1">Check P&L charts, review AI-detected invoice anomalies, and auto-dispatch customer outstanding reminders.</p>
                                    </div>
                                </button>
                            </div>
                        </div>

                        {/* Interactive UI Step Previews */}
                        <div className="lg:w-1/2 w-full relative">
                            <div className="absolute inset-0 bg-purple-500/5 blur-[90px] rounded-full pointer-events-none" />
                            <div className="relative rounded-3xl border border-slate-200/80 bg-slate-50 p-8 min-h-[300px] flex flex-col justify-center shadow-lg">
                                
                                {activeStep === 0 && (
                                    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-4">
                                        <span className="px-2 py-0.5 rounded bg-blue-50 border border-blue-100 text-blue-600 text-[9px] font-black uppercase">Configuration Panel</span>
                                        <h4 className="text-base font-bold text-slate-900">Profile Setup Mockup</h4>
                                        <div className="space-y-3">
                                            <div className="grid grid-cols-2 gap-3">
                                                <div className="space-y-1">
                                                    <span className="text-[9px] text-slate-400 font-bold uppercase">Business Name</span>
                                                    <div className="px-3.5 py-2 rounded-lg bg-white border border-slate-200/60 text-xs text-slate-800 font-medium shadow-sm">Rajesh Store Private Ltd</div>
                                                </div>
                                                <div className="space-y-1">
                                                    <span className="text-[9px] text-slate-400 font-bold uppercase">GSTIN / Tax ID</span>
                                                    <div className="px-3.5 py-2 rounded-lg bg-white border border-slate-200/60 text-xs text-slate-800 font-mono shadow-sm">07AAAAA1111A1Z1</div>
                                                </div>
                                            </div>
                                            <div className="space-y-1">
                                                <span className="text-[9px] text-slate-400 font-bold uppercase">UPI Handle for QR Codes</span>
                                                <div className="px-3.5 py-2 rounded-lg bg-white border border-slate-200 text-xs text-indigo-600 font-mono shadow-sm">rajeshstore@paytm</div>
                                            </div>
                                        </div>
                                    </motion.div>
                                )}

                                {activeStep === 1 && (
                                    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-4">
                                        <span className="px-2 py-0.5 rounded bg-emerald-50 border border-emerald-100 text-emerald-600 text-[9px] font-black uppercase">Active POS Cart</span>
                                        <h4 className="text-base font-bold text-slate-900">Billing Screen Summary</h4>
                                        <div className="space-y-2.5">
                                            <div className="flex justify-between items-center p-2.5 bg-white border border-slate-200/60 shadow-sm rounded-xl text-xs">
                                                <span className="text-slate-800 font-medium">Fortune Oil (2L) x 3</span>
                                                <span className="font-mono text-slate-800 font-bold">₹540.00</span>
                                            </div>
                                            <div className="flex justify-between items-center p-2.5 bg-white border border-slate-200/60 shadow-sm rounded-xl text-xs">
                                                <span className="text-slate-800 font-medium">Aashirvaad Atta (10kg) x 2</span>
                                                <span className="font-mono text-slate-800 font-bold">₹880.00</span>
                                            </div>
                                            <div className="flex justify-between items-center text-xs border-t border-slate-200 pt-2 font-bold text-slate-450">
                                                <span>Subtotal</span>
                                                <span className="font-mono text-slate-800">₹1,420.00</span>
                                            </div>
                                            <div className="flex justify-between items-center text-xs font-black text-slate-900">
                                                <span>Total GST (18%)</span>
                                                <span className="font-mono text-emerald-600">₹255.60</span>
                                            </div>
                                        </div>
                                    </motion.div>
                                )}

                                {activeStep === 2 && (
                                    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-4">
                                        <span className="px-2 py-0.5 rounded bg-purple-50 border border-purple-100 text-purple-650 text-[9px] font-black uppercase">Automated Audit</span>
                                        <h4 className="text-base font-bold text-slate-900">Invoice Anomalies Flagged</h4>
                                        <div className="space-y-2">
                                            <div className="p-3 rounded-xl bg-amber-50 border border-amber-100 flex gap-2.5 items-start text-xs shadow-sm">
                                                <div className="p-1 rounded bg-amber-100 text-amber-700">
                                                    <Info size={12} />
                                                </div>
                                                <div>
                                                    <p className="font-bold text-slate-850">Off-Hours Invoicing Alert</p>
                                                    <p className="text-[10px] text-slate-500 mt-0.5">Sale #INV-812 logged at 11:42 PM (Unusual hours).</p>
                                                </div>
                                            </div>
                                            <div className="p-3 rounded-xl bg-rose-50 border border-rose-100 flex gap-2.5 items-start text-xs shadow-sm">
                                                <div className="p-1 rounded bg-rose-100 text-rose-700">
                                                    <Info size={12} />
                                                </div>
                                                <div>
                                                    <p className="font-bold text-slate-850">Duplicate Invoice Scan</p>
                                                    <p className="text-[10px] text-slate-500 mt-0.5">Same customer + same total within 24 hours.</p>
                                                </div>
                                            </div>
                                        </div>
                                    </motion.div>
                                )}

                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* TESTIMONIAL / METRICS */}
            <section id="about" className="py-28 relative z-10 bg-[#F8FAFC] border-t border-slate-200/60">
                 <div className="max-w-7xl mx-auto px-6">
                     <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
                        <motion.div initial={{ opacity: 0, x: -30 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once:true }}>
                            <h2 className="text-xs font-bold uppercase tracking-widest text-emerald-600 mb-4">Our Philosophy</h2>
                            <h3 className="text-3xl sm:text-4xl font-black text-slate-900 mb-6 tracking-tight">Designed to empower the backbone of local trade.</h3>
                            <div className="space-y-6 text-slate-500 text-sm leading-relaxed font-medium">
                                <p>Large enterprises spend millions implementing complex ERP software to plug cash leaks and forecast balance sheets. Small business owners are typically left with clunky legacy software or simple pen-and-paper ledgers.</p>
                                <p><strong>FinSathi</strong> equalizes the playing field. We build software that offers premium design aesthetics, fast response speeds, and advanced forecasting calculations, yet remains simple enough to utilize on day one.</p>
                            </div>
                        </motion.div>

                        <div className="grid grid-cols-2 gap-4 w-full">
                            <div className="bg-white p-6 rounded-3xl border border-slate-200/60 text-center mt-6 shadow-sm space-y-1">
                                <h4 className="text-3xl sm:text-4xl font-black text-slate-905">15k+</h4>
                                <p className="text-[9px] text-slate-400 font-bold uppercase tracking-wider">Active Workspace Owners</p>
                            </div>
                            <div className="bg-white p-6 rounded-3xl border border-emerald-500/20 text-center shadow-[0_10px_30px_-10px_rgba(16,185,129,0.1)] space-y-1">
                                <h4 className="text-3xl sm:text-4xl font-black text-emerald-600">₹1B+</h4>
                                <p className="text-[9px] text-slate-400 font-bold uppercase tracking-wider">Invoices Handled</p>
                            </div>
                            <div className="bg-gradient-to-br from-blue-600/5 to-purple-600/5 p-8 rounded-3xl border border-slate-200/60 bg-white text-center col-span-2 shadow-sm space-y-3">
                                <p className="text-sm font-bold text-slate-800 italic">"FinSathi completely replaced my scattered billing spreadsheets. I track my batch margins and automated reminders on my phone."</p>
                                <div className="flex justify-center gap-0.5">
                                    {[1,2,3,4,5].map(i => <Star key={i} size={12} fill="#FBBF24" color="#FBBF24" />)}
                                </div>
                                <p className="text-[10px] text-slate-500 font-semibold">Rajesh K. · Retail Franchise Owner</p>
                            </div>
                        </div>
                     </div>
                 </div>
            </section>

            {/* FREQUENTLY ASKED QUESTIONS */}
            <section id="faq" className="py-28 relative z-10 bg-white border-t border-slate-200/60">
                <div className="max-w-4xl mx-auto px-6">
                    <div className="text-center mb-16">
                        <h2 className="text-xs font-bold uppercase tracking-widest text-purple-600 mb-3">Support & Answers</h2>
                        <h3 className="text-2xl sm:text-3xl font-black text-slate-900 mb-4 tracking-tight font-sans">Frequently Asked Queries</h3>
                        <p className="text-slate-500 text-xs sm:text-sm leading-relaxed">Find quick technical answers about our infrastructure and tools below.</p>
                    </div>

                    <div className="space-y-4">
                        {faqData.map((item, idx) => (
                            <div key={idx} className="border border-slate-200/80 bg-slate-50/50 rounded-2xl overflow-hidden transition-all duration-300 shadow-sm">
                                <button 
                                    className="w-full px-6 py-4 flex justify-between items-center text-left hover:bg-slate-50 transition-colors"
                                    onClick={() => setActiveFaq(activeFaq === idx ? null : idx)}
                                >
                                    <span className="text-xs sm:text-sm font-bold text-slate-800">{item.q}</span>
                                    {activeFaq === idx ? <ChevronUp size={16} className="text-slate-500" /> : <ChevronDown size={16} className="text-slate-500" />}
                                </button>
                                
                                <AnimatePresence initial={false}>
                                    {activeFaq === idx && (
                                        <motion.div 
                                            initial={{ height: 0 }}
                                            animate={{ height: 'auto' }}
                                            exit={{ height: 0 }}
                                            className="overflow-hidden"
                                        >
                                            <p className="px-6 pb-5 pt-1 text-slate-500 text-xs sm:text-sm leading-relaxed font-medium">
                                                {item.a}
                                            </p>
                                        </motion.div>
                                    )}
                                </AnimatePresence>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* HOW TO JOIN */}
            <section className="py-28 relative z-10 border-t border-slate-200/60 bg-[#F8FAFC]">
                <div className="max-w-4xl mx-auto px-6 text-center">
                    <motion.div 
                        initial={{ opacity:0, y: 20 }} 
                        whileInView={{ opacity:1, y:0 }} 
                        viewport={{ once:true }} 
                        className="p-[1px] rounded-[2.5rem] bg-gradient-to-r from-blue-500 via-indigo-500 to-purple-500 shadow-lg"
                    >
                        <div className="bg-white rounded-[39px] px-8 py-14 sm:px-14 sm:py-20 space-y-8">
                            <h3 className="text-3xl sm:text-4xl font-black text-slate-900 tracking-tight">Ready to scale your business?</h3>
                            <p className="text-slate-500 text-xs sm:text-sm max-w-xl mx-auto leading-relaxed">
                                Join hundreds of growing retailers modernizing their workflows, checking profit leaks, and receiving due payments faster.
                            </p>
                            <div className="flex flex-col sm:flex-row justify-center gap-4">
                                <Link to="/register" className="px-8 py-3.5 bg-blue-600 text-white font-black text-xs uppercase tracking-wider rounded-full hover:bg-blue-700 transition-all shadow-md shadow-blue-500/10">
                                    Start Free Trial
                                </Link>
                                <button onClick={() => scrollToSection('#demo')} className="px-8 py-3.5 bg-transparent border border-slate-200 text-slate-700 font-bold text-xs uppercase tracking-wider rounded-full hover:bg-slate-50 transition-all">
                                    Interactive Demo
                                </button>
                            </div>
                        </div>
                    </motion.div>
                </div>
            </section>

            {/* FOOTER */}
            <footer className="py-12 bg-white border-t border-slate-200/60 relative z-10 text-slate-500 text-xs">
                <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-8">
                    <div className="flex items-center gap-3">
                        <div className="relative">
                            <div className="absolute inset-0 bg-blue-600/20 blur-[6px] rounded-full" />
                            <img src={logo} alt="FinSathi" className="w-6 h-6 object-contain relative z-10" />
                        </div>
                        <span className="font-black text-slate-800 text-base tracking-tight">FinSathi</span>
                    </div>
                    <div className="text-[11px] font-medium text-slate-400 text-center md:text-left">
                        &copy; {new Date().getFullYear()} FinSathi Digital Technologies. All rights reserved.
                    </div>
                    <div className="flex gap-6 font-bold text-slate-400">
                        <a href="#" className="hover:text-slate-650 transition-colors">Privacy Policy</a>
                        <a href="#" className="hover:text-slate-650 transition-colors">Terms of Service</a>
                        <a href="#" className="hover:text-slate-650 transition-colors">Support Desk</a>
                    </div>
                </div>
            </footer>
        </div>
    );
};

// Sub-components
const FeatureBox = ({ icon: Icon, title, desc, delay }) => (
    <motion.div 
        initial={{ opacity: 0, y: 25 }} 
        whileInView={{ opacity: 1, y: 0 }} 
        viewport={{ once: true }} 
        transition={{ delay, duration: 0.5 }}
        className="p-8 rounded-[2rem] bg-slate-50/50 border border-slate-200/60 hover:border-slate-350 hover:bg-slate-50 transition-all duration-300 group hover:-translate-y-1.5 shadow-sm"
    >
        <div className="w-11 h-11 rounded-xl bg-white border border-slate-200 flex items-center justify-center mb-6 text-slate-800 group-hover:scale-105 group-hover:border-blue-500/40 transition-all duration-300 shadow-sm">
            <Icon size={20} />
        </div>
        <h3 className="text-base font-bold mb-2.5 text-slate-900">{title}</h3>
        <p className="text-slate-500 leading-relaxed text-xs font-medium">
            {desc}
        </p>
    </motion.div>
);

export default LandingPage;
